const whenText = [
  "Pred tvojim narodením bola dobrá doba.",
  "Keď po zemi chodili dinosaury a Zdena Studenková",
  "Keď ti kokot stuhne",
  "Keď budeš pekný, takže je to v piči",
  "Keď Zdena ešte s Krónerom hádzali kopije na mamuty",
  "Zajtra",
  "Na svätého Dyndy",
  "Keď sa prestaneš pýtať pičoviny",
  "Dones mi colu a porozprávame sa ",
  "Spokojnosť aj pre teba",
  "Včera bolo neskoro",
  "Vravia že lásky dáávno niät",
  "Keď Zdena vymyslela klinové písmo",
  "Na ďalšie Vianoce. A skús menej fetovať",
  "NIKDY",
  "Za hodku.",
  "Ešte jednu epizódu pozri",
  "Daj dve ARAMky a uvidíme",
  "Dneska určite nie.",
  "Až mesiac príde do 35% zatmenia",
  "O 9:38 ráno.",
  "Keď Peťovi narastú vlasy",
  "Po tom ako si spolu pozrieme Večerníčka",
  "Na jarmoku, vidíme sa",
  "Možno na tvojom pohrebe.",
];

module.exports = whenText;
