const whereText = [
  "V lone tvojho špinavého tatka.",
  "Za pôrodnicou doľava.",
  "Ja nevjem uš.",
  "Povedz si sám, dáme stretko ty diviačik ššalenyy",
  "Tuším že sa to celé odohralo v Mjarmiarsku",
  "Tam kde by sa nikto dobrovolne nepozrel - do Rasťovej čokodierky",
  "Akože veď nebuď hlúpy, čo nevieš?",
  "Kľudne choď do piče",
  "Pri spotených ponožkách tvojej transgender matky",
  "Hľadal som ale jebäť",
  "Skoč",
  "STU učilište",
  "Kde bolo tam bolo, Jakub búchal po stole kokotom",
  "Bastila. Oh wait <:GaboHolik:934061170246156358>",
  "U Rastíka na byte <:MonikaFound:934906718389944353>",
  "Môže byť u mňa doma?",
  "Roman ťa už čaká <:MonikaFound:934906718389944353>",
  "No to je jasné, pod mostom",
  "Tam kde sa zdržiavajú staršie pani",
  "Zajtra. Aha počkať..  v Tescu.",
  "Tak toto ani v Lidli nezoženieš",
  "Možno v bordeli nájdeš odpoveď.",
  "Ani u teba doma by toto neprešlo.",
  "Ideálne čo najďalej. Skús Mariánsku priekopu.",
  "Jeb sa na to. Choď sa prejsť.",
  "Miestnosť 47, Gymnázium VBN. Budem tam.",
];

module.exports = whereText;
