const whoText = [
  "Tvoja mamka <:MonikaFound:934906718389944353>",
  "Tvoj Tatko",
  "Pápež",
  "Andrej Kiska",
  "Branislav Mojsej",
  "Romanove pravé vajce",
  "Neviem, spýtaj sa @Adam",
  "Mám na toto odpovedať?",
  "Akože skús sa zamyslieť radšej nad svojím životom",
  "Ten koho netreba vetovať",
  "Hubapičariť",
  "Čapútová alebo ŠoroŠ",
  "Pil C a Separ",
  "<@503252604038414353> a jeho smradľavé slipky",
  "Dušan určite nie",
  "Sfúkaný ego na bicykli",
  "Kaliňák so stoporenou predkožkou bežiaci na Somálskom maratóne",
  "Martinga z Turca",
  "Tvojho Otca Koňa Brat",
  "Dobrá otázka ale mali by ti zobrať občiansky",
  "Všetci ti môžu závidieť",
  "Dobre a načo ti bude táto informácia?",
  "Robo Kazík čo ho jazdí kamzík",
  "Nohy jak tvoj toci cez víkend",
  "Tvoj tatko čo jazdí na tvojej hrdzavej sestre",
  "Len a len ty <:JakubDab:749317841701830697>",
  "Monika <:MonikaFound:934906718389944353>",
  "🤷",
  "Nikky <:nikkyziadnetricky:729090921496576030>",
  "Holá ťa pozdravuje",
  "Bazén s klasickými rozmermi.",
  "Najebaný Matúš na felde",
];

module.exports = whoText;
