const whoText = [
  "Tvoja mamka",
  "Tvoj Tatko",
  "Pápež",
  "Andrej Kiska",
  "Branislav Mojsej",
  "Romanove pravé vajce",
  "Neviem, spýtaj sa <@563689829116674068>",
  "Mám na toto odpovedať?",
  "Akože skús sa zamyslieť radšej nad svojím životom",
  "Ten koho netreba vetovať",
  "Hubapičariť",
  "Čapútová alebo ŠoroŠ",
  "Pil C a Separ",
  "<@503252604038414353> a jeho smradľavé slipky",
  "Dušan určite nie",
  "Sfúkaný ego na bicykli",
  "Kaliňák so stoporenou predkožkou bežiaci na Somálskom maratóne",
  "Martinga z Tuhca",
  "Tvojho Otca Koňa Brat",
  "Dobrá otázka ale mali by ti zobrať občiansky",
  "Všetci ti môžu závidieť",
  "Dobre a načo ti bude táto informácia?",
  "Robo Kazík čo ho jazdí kamzík",
  "Nohy jak tvoj toci cez víkend",
  "Tvoj tatko čo jazdí na tvojej hrdzavej sestre",
];

module.exports = whoText;
