const whyText = [
  "Pretože kokot s kokotom je vlastne nepolárny kokot a keď si nepolárny kokot tak máš právo na úplnú piču a vlastne piču dostaneš, takže teraz by si mal prestať naťahovať tvoj polárny kokot a natiahni sa sám aby ti už nebolo zle a bol si menší kokot",
  "Pretože keď si sa narodil tak vlastne tvojej mamke odjebalo nosohltan z tých zvratkov, ktoré nagniavila na doktora, ktorý ťa jej podával, pretože keď ťa uvidela tak ju strašne dojebalo z toho že musela vynosiť 9 mesiacov a vznikol z teba takýto pytel hovien ",
  "No neviem ale podľa mňa iba pretože si neprehltnutý tak preto ti tak jebe",
  "Dosť bolo pičovín, siahni si na život",
  "Neviem síce prečo to tak je ale skôr je lepšia otázka, prečo som tak toxický?",
  "Vesmír to tak chcel",
  "Noo veci sa majú takto… pán Boh to tak stvoril a nikto sa na to už potom nepýtal",
  "Neviem prečo sa ma túto prečo otázku pýtaš a už by si s tým mohol prestať",
  "Pretože 1+1 nikdy nebolo viac ako 2 a ani menej ako 2 takže vlastne všetko je tak ako má byť a nie si až taká piča ako si o sebe myslíš",
  "Dobrú chuť aj tebe",
  "Pretože mi Táňa zakázala",
  "Pretože ma to nebaví, vieš čo to je furt tu odpovedať ľudom ako ty?",
  "Neviem akože, skús o chvíľu",
  "Ďakujem Vám pekne za vaše otázky",
  "NENI ŠANCA",
  "No neviem ti takto z hlavy povedať, mal by si skúsiť crack",
  "Pretože pri pôrode si vypadol z rúk sestričke a lebku ti lepili ako puzzle. Áno presne preto",
  "Neber mi tú flašu z ruky lebo ťa pošlem naspäť do matky",
  "Svieť",
  "Radšej sa zamysli nad sebou",
  "Darovanej flaši na kolok nepozeraj",
  "Tetičko, promiň, zatím o tom mluvit nechci. Nechceš mi radši vyprávět o AIDS?",
];

module.exports = whyText;
